<?php

namespace TDN\Bundle\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultatsQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatsQuizRepository extends EntityRepository
{
}
