<?php

namespace TDN\Bundle\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionQuizRepository extends EntityRepository
{
}
